### ISSUE TITLE
请问可以提供一份使用Maven来导入依赖的demo项目吗？

### ISSUE THREAD

**Issue by maoweijiajia** [kosaka-bun/jar-launcher#5]
请问可以提供一份使用Maven来导入依赖的demo项目吗？

不会使用Gradle 来导入依赖  通过Maven导入依赖也一直无法导入成功，或者说是我的依赖导入方式有问题吗？

麻烦大大帮忙看一下或者提供一个Maven依赖的项目，万分感谢

<repositories>
    <repository>
        <id>honoka-maven-repo</id>
        <url>https://raw.githubusercontent.com/kosaka-bun/maven-repo/master/repository/release</url>
    </repository>
</repositories>
<dependencies>
        <dependency>
            <groupId>de.honoka.qqrobot</groupId>
            <artifactId>qqrobot-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>

**Comment by kosaka-bun** [comment]
您可以提供一下您的pom.xml文件内容，以便分析。

此外，如果您正在开发自己的个人项目，强烈建议您不再使用Maven。

**Comment by maoweijiajia** [comment]
我通过 Gradle 成功导入了依赖，我是一个java初学者， 想了解一下您为什么会不建议使用 Maven？ （PS：不方便说也可以。。）
下边是我的Maven依赖
[pom.txt](https://github.com/user-attachments/files/17988853/pom.txt)

**Comment by kosaka-bun** [comment]
Maven在现在已经是一款落后的构建工具了，基本不再更新，基于XML的构建配置文件也十分冗杂、不灵活。

Gradle的构建脚本是基于Groovy或Kotlin脚本的，您在构建脚本中可以根据一些复杂的逻辑来决定对一个项目采用哪些配置，这对多模块项目来说是极为有用的，比如您可以根据工程名后缀的不同，来实现只写两套依赖配置，作用于两个或更多个子模块的效果，这是Maven所难以做到的。

此外，Gradle的插件也比Maven更易配置、易理解，许多插件还可以开箱即用，一行命令导入即可。

如果您有兴趣，可以参考下本项目或我的另一个项目——honoka-sdk中的Gradle脚本，或许可以从中理解Gradle的设计思路及灵活性。

**Comment by maoweijiajia** [comment]
好的谢谢，我会去了解学习 Gradle 构建脚本的 感谢您的回答。
