### ISSUE TITLE
我在使用提供的demo项目时，正式环境下已可读取群消息与好友数据 但是发消息没有反应

### ISSUE THREAD

**Issue by maoweijiajia** [kosaka-bun/jar-launcher#7]
QQ 打开了两个一个是 webSocket 服务 一个是  http服务  我还需要做什么吗？麻烦大佬看看。研究好久了。。谢谢了。

2024-12-06T17:36:03.969+08:00  INFO 20464 --- [pool-2-thread-1] d.h.q.f.i.o.component.ContactManager     : 读取了3个好友信息
2024-12-06T17:36:03.973+08:00  INFO 20464 --- [pool-2-thread-1] d.h.q.f.i.o.component.ContactManager     : 读取了2个群信息
2024-12-06T17:36:04.079+08:00  INFO 20464 --- [           main] d.h.q.s.component.logger.LoggerServer    : Logger Data Source: jdbc:h2:C:\Users\Administrator\Desktop\demo-projects-master\qqrobot-demo\build\classes\java\main\qqrobot\log
2024-12-06T17:36:04.712+08:00  INFO 20464 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8081 (http) with context path '/qqrobot-demo'
2024-12-06T17:36:04.729+08:00  INFO 20464 --- [           main] de.honoka.qqrobot.demo.QqRobotDemo       : Started QqRobotDemo in 2.983 seconds (process running for 4.0)
2024-12-06T17:36:04.790+08:00  INFO 20464 --- [cTaskExecutor-1] d.h.q.f.impl.onebot.OnebotFramework      : WebSocket连接已建立
2024-12-06T17:36:04.803+08:00  INFO 20464 --- [pool-2-thread-2] d.h.q.f.impl.onebot.OnebotFramework      : QQ已在线，5秒后开始处理消息
2024-12-06T17:36:09.808+08:00  INFO 20464 --- [pool-2-thread-3] d.h.q.f.impl.onebot.OnebotFramework      : 已开始处理消息

**Comment by maoweijiajia** [comment]
忘记说了。。 这个样子无法接收到消息，无论是群聊消息还是个人消息。。不好意思

**Comment by kosaka-bun** [comment]
您使用的OneBot框架是基于OneBot 11标准的吗？

您还可以参考[这篇文章](https://github.com/botuniverse/onebot-11/blob/master/communication/ws.md)，手动使用工具连接一下您的框架，看看您的框架是否正确提供了WebSocket消息。

**Comment by maoweijiajia** [comment]
我连接了WebSocket消息检查了结果  这个信息是有误的吗？或者说是不符合规则的吗？ 我通过WebSocket 来发送消息是可行的

收到消息 格式为18:24:19
{
	"self_id": 2058709391,
	"user_id": 1304475843,
	"time": 1733480878,
	"message_id": 1288606122,
	"message_seq": 1288606122,
	"real_id": 1288606122,
	"message_type": "private",
	"sender": {
		"user_id": 此处有值,
		"nickname": "123",
		"card": ""
	},
	"raw_message": "你好",
	"font": 14,
	"sub_type": "friend",
	"message": "你好",
	"message_format": "string",
	"post_type": "message",
	"target_id": 1304475843,
	"raw": {
		"msgId": "7445243685371521470",
		"msgRandom": "256518873",
		"msgSeq": "90",
		"cntSeq": "0",
		"chatType": 1,
		"msgType": 2,
		"subMsgType": 1,
		"sendType": 0,
		"senderUid": "u_wZBUosNZL9jihKqL0h_pIA",
		"peerUid": "u_wZBUosNZL9jihKqL0h_pIA",
		"channelId": "",
		"guildId": "",
		"guildCode": "0",
		"fromUid": "0",
		"fromAppid": "0",
		"msgTime": "1733480878",
		"msgMeta": {},
		"sendStatus": 2,
		"sendRemarkName": "",
		"sendMemberName": "",
		"sendNickName": "",
		"guildName": "",
		"channelName": "",
		"elements": [{
			"elementType": 1,
			"elementId": "7445243685371521469",
			"elementGroupId": 0,
			"extBufForUI": {},
			"textElement": {
				"content": "你好",
				"atType": 0,
				"atUid": "0",
				"atTinyId": "0",
				"atNtUid": "",
				"subElementType": 0,
				"atChannelId": "0",
				"linkInfo": null,
				"atRoleId": "0",
				"atRoleColor": 0,
				"atRoleName": "",
				"needNotify": 0
			},
			"faceElement": null,
			"marketFaceElement": null,
			"replyElement": null,
			"picElement": null,
			"pttElement": null,
			"videoElement": null,
			"grayTipElement": null,
			"arkElement": null,
			"fileElement": null,
			"liveGiftElement": null,
			"markdownElement": null,
			"structLongMsgElement": null,
			"multiForwardMsgElement": null,
			"giphyElement": null,
			"walletElement": null,
			"inlineKeyboardElement": null,
			"textGiftElement": null,
			"calendarElement": null,
			"yoloGameResultElement": null,
			"avRecordElement": null,
			"structMsgElement": null,
			"faceBubbleElement": null,
			"shareLocationElement": null,
			"tofuRecordElement": null,
			"taskTopMsgElement": null,
			"recommendedMsgElement": null,
			"actionBarElement": null,
			"prologueMsgElement": null
		}],
		"records": [],
		"emojiLikesList": [],
		"commentCnt": "0",
		"directMsgFlag": 0,
		"directMsgMembers": [],
		"peerName": "",
		"freqLimitInfo": null,
		"editable": false,
		"avatarMeta": "",
		"avatarPendant": "",
		"feedId": "",
		"roleId": "0",
		"timeStamp": "0",
		"clientIdentityInfo": null,
		"isImportMsg": false,
		"atType": 0,
		"roleType": 0,
		"fromChannelRoleInfo": {
			"roleId": "0",
			"name": "",
			"color": 0
		},
		"fromGuildRoleInfo": {
			"roleId": "0",
			"name": "",
			"color": 0
		},
		"levelRoleInfo": {
			"roleId": "0",
			"name": "",
			"color": 0
		},
		"recallTime": "0",
		"isOnlineMsg": true,
		"generalFlags": {},
		"clientSeq": "4928",
		"fileGroupSize": null,
		"foldingInfo": null,
		"multiTransInfo": null,
		"senderUin": "1304475843",
		"peerUin": "1304475843",
		"msgAttrs": {},
		"anonymousExtInfo": null,
		"nameType": 0,
		"avatarFlag": 0,
		"extInfoForUI": null,
		"personalMedal": null,
		"categoryManage": 0,
		"msgEventInfo": null,
		"sourceType": 1,
		"id": 1288606122
	}
}

但是在项目中无法获取到这个消息

**Comment by kosaka-bun** [comment]
您收到的WebSocket消息中的`message`字段为`string`类型，不符合OneBot 11标准。

请参考[文档](https://github.com/botuniverse/onebot-11/blob/master/event/message.md)。
